### ISSUE TITLE
Extra Window opens and shuts immediately

### ISSUE THREAD

**Issue by benmccormick** [tmux-plugins/tmux-fpp#2]
When I try to use this plugin, I see the extra tmux window appear, but it immediately shuts without me switching to it.  I cleared tmux conf down to simply loading this and the plugin loader and saw the same issue.

This is on OSX Yosemite in iTerm2, the only irregularity I have is that I use Fish Shell instead of bash/zsh/etc.

**Comment by jbnicolai** [comment]
Do you have any paths in your current window's buffer? Could you test running any command that prints paths, and trying again? I think it's related to facebook/PathPicker#102, where fpp won't exit with a nonzero exit code if it fails to find paths.

I think this is what is happening:

[![Demo tmux-fpp issue](http://g.recordit.co/ksEimJ0wyf.gif)](http://recordit.co/ksEimJ0wyf)

**Comment by benmccormick** [comment]
Hmm, no I definitely do have file paths in my history.  I've been testing by running an ack command and/or git status to generate a file list and then running.  I don't get anything.  Any advice on how to test what the plugin is receiving so I can make sure that the window is being passed correctly?

**Comment by benmccormick** [comment]
So this is the real issue: https://github.com/fish-shell/fish-shell/issues/150 :(

Not sure what the best way to fix that is since you can't really force it to use bash in that context.  I've forked the repo for now: https://github.com/benmccormick/tmux-fpp-fish for my own use

**Comment by jbnicolai** [comment]
@benmccormick thanks for the persistence in hunting down the issue!

> Not sure what the best way to fix that is since you can't really force it to use bash in that context

Can't you? How about I change [this](https://github.com/tmux-plugins/tmux-fpp/blob/master/fpp.tmux#L18) to:

``` bash
    new-window -c "#{pane_current_path}" "/bin/sh -c 'cat /tmp/tmux-buffer | fpp && rm /tmp/tmux-buffer'"
```

I think this should work. Let me give it a quick test and report back :)

**Comment by jbnicolai** [comment]
@benmccormick good news, it seems to now work in `fish` shell as well
