### ISSUE TITLE
typo in project description - 'temrinal '

### ISSUE THREAD

**Issue by snoblenet** [tmux-plugins/tmux-fpp#20]
The is a typo in the project description - 'temrinal '

**Comment by ZaydH** [comment]
This issue is different than #6.  

<img width="537" alt="image" src="https://user-images.githubusercontent.com/6292018/64614220-d5f50e80-d38c-11e9-9083-53df90a9be8d.png">

**Comment by KapJI** [comment]
This was fixed, thank you!
