### ISSUE TITLE
'$ ll' work well , but '$ ls' work bad!

### ISSUE THREAD

**Issue by xinyu-io** [tmux-plugins/tmux-fpp#25]
![image](https://user-images.githubusercontent.com/32320149/75601691-91a32980-5af8-11ea-84a2-ef89dc0e1271.png)

Then `$ ls | fpp`
![image](https://user-images.githubusercontent.com/32320149/75601661-47ba4380-5af8-11ea-8da9-fdf15b70064f.png)

**Comment by KapJI** [comment]
This is current limitation of `fpp`, it can only detect one path per line.

**Comment by KapJI** [comment]
It's not `tmux-fpp` issue, I'm going to close this. Feel free to open another issue on https://github.com/facebook/pathpicker/
I have this in my plans but there is timeline.
