### ISSUE TITLE
Not working on macOS Catalina

### ISSUE THREAD

**Issue by jmolero** [tmux-plugins/tmux-fpp#26]
Hi,

I've been using this plugin for some time now but it stopped working and I didn't make any config change. 

I was thinking that may be since I updated to macOS Catalina because the  bind-key looks like this:
```
bind-key -T prefix       f                 capture-pane -J \; save-buffer /var/folders/_d/pl4l0yy16s78vbnmjxhx95sc0000gn/T//tmux-buffer \; delete-buffer \; new-window -c "#{pane_current_path}" -n fpp "sh -c 'cat \"/var/folders/_d/pl4l0yy16s78vbnmjxhx95sc0000gn/T//tmux-buffer\" | fpp ; rm \"/var/folders/_d/pl4l0yy16s78vbnmjxhx95sc0000gn/T//tmux-buffer\"'"
```

I had problems with other vim plugins because of these weird temporary folders used. 

Thanks!

**Comment by KapJI** [comment]
Try the latest version, it should work on Catalina. If it doesn't work, feel free to reopen.
